# Generated by Django 4.2 on 2023-04-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='about_imgs')),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='achievement_imgs')),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_text', models.CharField(max_length=20)),
                ('orange_text', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='gallery_imgs')),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(max_length=1000)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Shop_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='shop_item_imgs')),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Tea_cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='tea_imgs')),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='testimonial_imgs')),
                ('photo', models.ImageField(upload_to='client_testimonial_imgs')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
