# Generated by Django 4.2 on 2023-04-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_about_is_visible_achievements_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'leftt'), (2, 'middle-1'), (3, 'middle-2'), (4, 'middle-3'), (5, 'right')], unique=True),
        ),
    ]
