# Generated by Django 4.2 on 2023-04-21 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_achievements_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number is wated in "+380xx xxx xx xx" format', regex='^\\+?3?8?0?\\d{2}[- ]?(\\d[- ]?){7}$')])),
                ('message', models.TextField(max_length=2000)),
                ('date_request', models.DateTimeField(auto_now_add=True)),
                ('date_response', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date_request',),
            },
        ),
    ]
